"""Shared pytest configuration and database fixtures.

Environment setup must happen before anything imports ``app``: ``api/.env`` supplies
``DATABASE_URL_TEST`` locally. ``DATABASE_URL`` is then *overwritten* with a placeholder so no
test can ever inherit the dev database URL from ``api/.env``; tests that need a database use the
``test_database_url`` fixture, which refuses non-``_test`` databases.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

API_ROOT = Path(__file__).resolve().parents[1]

load_dotenv(API_ROOT / ".env", override=False)
os.environ["DATABASE_URL"] = "postgresql+psycopg://localhost/unused"
os.environ.setdefault("ENVIRONMENT", "local")

from collections.abc import Iterator
from dataclasses import dataclass
from uuid import UUID, uuid4

import pytest
from alembic import command
from alembic.config import Config
from hypothesis import settings
from sqlalchemy import Engine, create_engine
from sqlalchemy.engine import make_url
from sqlalchemy.orm import Session
from sqlalchemy.pool import NullPool

from app.config import normalize_database_url
from app.db.models import (
    AllocationSnapshot,
    Assignment,
    Correction,
    Household,
    ParseAttempt,
    Participant,
    Receipt,
    User,
)

settings.register_profile("dev", max_examples=100)
settings.register_profile("ci", max_examples=500, derandomize=True)
settings.load_profile(os.environ.get("HYPOTHESIS_PROFILE", "dev"))


@pytest.fixture(scope="session")
def test_database_url() -> str:
    url = os.environ.get("DATABASE_URL_TEST")
    if not url:
        if os.environ.get("REQUIRE_DB_TESTS") == "1":
            pytest.fail("DATABASE_URL_TEST not set")
        pytest.skip("DATABASE_URL_TEST not set")
    normalized = normalize_database_url(url)
    database = make_url(normalized).database or ""
    if not database.endswith("_test"):
        pytest.fail("refusing to run against non-test database")
    return normalized


@pytest.fixture(scope="session")
def alembic_config(test_database_url: str) -> Config:
    cfg = Config(str(API_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(API_ROOT / "alembic"))
    cfg.attributes["connection_url"] = test_database_url
    # Don't let alembic's fileConfig replace pytest's logging handlers.
    cfg.attributes["configure_logger"] = False
    return cfg


@pytest.fixture(scope="session")
def migrated_engine(alembic_config: Config, test_database_url: str) -> Iterator[Engine]:
    """Single owner of test-database schema state for the whole session."""
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")
    engine = create_engine(test_database_url, poolclass=NullPool)
    yield engine
    engine.dispose()
    command.downgrade(alembic_config, "base")


@pytest.fixture
def db_session(migrated_engine: Engine) -> Iterator[Session]:
    """A session whose writes are rolled back after each test."""
    connection = migrated_engine.connect()
    transaction = connection.begin()
    session = Session(bind=connection, join_transaction_mode="create_savepoint")
    try:
        yield session
    finally:
        session.close()
        transaction.rollback()
        connection.close()


@dataclass(frozen=True)
class Graph:
    user_id: UUID
    household_id: UUID
    payer_id: UUID
    member_id: UUID
    receipt_id: UUID
    attempt_id: UUID
    correction_id: UUID
    snapshot_id: UUID


def make_graph(session: Session) -> Graph:
    """Insert one fully-linked household → receipt → attempt → children graph.

    IDs are generated by the database, so each parent is flushed before its id is used.
    """
    user = User(email=f"{uuid4()}@test.local")
    session.add(user)
    session.flush()

    household = Household(owner_user_id=user.id, name="Test House")
    session.add(household)
    session.flush()

    payer = Participant(household_id=household.id, display_name="P1", sort_order=0)
    member = Participant(household_id=household.id, display_name="P2", sort_order=1)
    session.add_all([payer, member])
    session.flush()

    receipt = Receipt(
        household_id=household.id, payer_participant_id=payer.id, status="needs_review"
    )
    session.add(receipt)
    session.flush()

    attempt = ParseAttempt(
        receipt_id=receipt.id,
        attempt_number=1,
        trigger="initial",
        provider="test",
        model="test",
        prompt_version="v0",
        outcome="ok",
    )
    session.add(attempt)
    session.flush()

    receipt.active_parse_attempt_id = attempt.id
    session.flush()

    correction = Correction(
        receipt_id=receipt.id,
        parse_attempt_id=attempt.id,
        sequence=1,
        kind="update_line",
        line_id="L1",
        payload={},
    )
    assignment = Assignment(parse_attempt_id=attempt.id, line_id="L1", participant_id=member.id)
    snapshot = AllocationSnapshot(
        receipt_id=receipt.id,
        parse_attempt_id=attempt.id,
        allocator_version="1",
        input={},
        result={},
    )
    session.add_all([correction, assignment, snapshot])
    session.flush()
    session.refresh(receipt)

    return Graph(
        user_id=user.id,
        household_id=household.id,
        payer_id=payer.id,
        member_id=member.id,
        receipt_id=receipt.id,
        attempt_id=attempt.id,
        correction_id=correction.id,
        snapshot_id=snapshot.id,
    )
