"""Shared pytest configuration and database fixtures.

Environment setup must happen before anything imports ``app``: ``api/.env`` supplies
``DATABASE_URL_TEST`` locally. ``DATABASE_URL`` is then *overwritten* with a placeholder so no
test can ever inherit the dev database URL from ``api/.env``; tests that need a database use the
``test_database_url`` fixture, which refuses non-``_test`` databases.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

API_ROOT = Path(__file__).resolve().parents[1]

load_dotenv(API_ROOT / ".env", override=False)
os.environ["DATABASE_URL"] = "postgresql+psycopg://localhost/unused"
os.environ.setdefault("ENVIRONMENT", "local")

from collections.abc import Callable, Iterator
from dataclasses import dataclass
from uuid import UUID

import pytest
from alembic import command
from alembic.config import Config
from fastapi.testclient import TestClient
from hypothesis import settings
from sqlalchemy import Engine, create_engine
from sqlalchemy.engine import make_url
from sqlalchemy.orm import Session
from sqlalchemy.pool import NullPool

from app.config import Settings, normalize_database_url
from app.db.models import Correction, ParseAttempt, Receipt
from app.db.session import get_session
from app.main import create_app
from app.ratelimit import RateLimits

settings.register_profile("dev", max_examples=100)
settings.register_profile("ci", max_examples=500, derandomize=True)
settings.load_profile(os.environ.get("HYPOTHESIS_PROFILE", "dev"))


@pytest.fixture(scope="session")
def test_database_url() -> str:
    url = os.environ.get("DATABASE_URL_TEST")
    if not url:
        if os.environ.get("REQUIRE_DB_TESTS") == "1":
            pytest.fail("DATABASE_URL_TEST not set")
        pytest.skip("DATABASE_URL_TEST not set")
    normalized = normalize_database_url(url)
    database = make_url(normalized).database or ""
    if not database.endswith("_test"):
        pytest.fail("refusing to run against non-test database")
    return normalized


@pytest.fixture(scope="session")
def alembic_config(test_database_url: str) -> Config:
    cfg = Config(str(API_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(API_ROOT / "alembic"))
    cfg.attributes["connection_url"] = test_database_url
    # Don't let alembic's fileConfig replace pytest's logging handlers.
    cfg.attributes["configure_logger"] = False
    return cfg


@pytest.fixture(scope="session")
def migrated_engine(alembic_config: Config, test_database_url: str) -> Iterator[Engine]:
    """Single owner of test-database schema state for the whole session."""
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")
    engine = create_engine(test_database_url, poolclass=NullPool)
    yield engine
    engine.dispose()
    command.downgrade(alembic_config, "base")


@pytest.fixture
def db_session(migrated_engine: Engine) -> Iterator[Session]:
    """A session whose writes are rolled back after each test."""
    connection = migrated_engine.connect()
    transaction = connection.begin()
    session = Session(bind=connection, join_transaction_mode="create_savepoint")
    try:
        yield session
    finally:
        session.close()
        transaction.rollback()
        connection.close()


TEST_ORIGIN = "http://localhost:3000"

ClientFactory = Callable[..., TestClient]


class FakeClock:
    """A controllable clock for the rate limiter: advance it by setting ``now``."""

    def __init__(self) -> None:
        self.now = 1000.0

    def __call__(self) -> float:
        return self.now


@pytest.fixture
def api_client(db_session: Session) -> Iterator[ClientFactory]:
    """Build a TestClient whose routes use ``db_session`` (commits become savepoints).

    Keyword arguments go to ``create_app`` (``rate_limits``, ``clock``). ``raise_server_exceptions``
    is off so tests see the JSON 500 a browser would.
    """
    clients: list[TestClient] = []

    def factory(
        rate_limits: RateLimits | None = None, clock: Callable[[], float] | None = None
    ) -> TestClient:
        settings = Settings(
            _env_file=None,
            database_url="postgresql+psycopg://localhost/unused",
            environment="local",
            cors_allowed_origins=[TEST_ORIGIN],
        )
        app = create_app(settings, rate_limits=rate_limits, clock=clock)

        def session_override() -> Iterator[Session]:
            yield db_session

        app.dependency_overrides[get_session] = session_override
        client = TestClient(app, raise_server_exceptions=False, headers={"Origin": TEST_ORIGIN})
        clients.append(client)
        return client

    yield factory
    for client in clients:
        client.close()


@dataclass(frozen=True)
class Graph:
    receipt_id: UUID
    attempt_id: UUID
    correction_id: UUID


def make_graph(session: Session) -> Graph:
    """Insert one receipt -> parse attempt -> correction graph.

    IDs are generated by the database, so each parent is flushed before its id is used.
    """
    receipt = Receipt(status="needs_review")
    session.add(receipt)
    session.flush()

    attempt = ParseAttempt(
        receipt_id=receipt.id,
        attempt_number=1,
        trigger="initial",
        provider="test",
        model="test",
        prompt_version="v0",
        outcome="ok",
    )
    session.add(attempt)
    session.flush()

    receipt.active_parse_attempt_id = attempt.id
    correction = Correction(
        receipt_id=receipt.id,
        parse_attempt_id=attempt.id,
        sequence=1,
        kind="update_line",
        line_id="L1",
        payload={},
    )
    session.add(correction)
    session.flush()
    session.refresh(receipt)

    return Graph(receipt_id=receipt.id, attempt_id=attempt.id, correction_id=correction.id)
